### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by jsilvestre**
* Fixed a previous commit where a part was missing (I forgot to push apparently...sorry).
* Fixed a bug where times were not updated accordingly to each other. Be aware that it doesn't take edge cases into account (i.e. if you change day), because they are tricky.
* Fixed pointers on icon of the popover's main screen.
* Added tooltips on popover's main screen's icons.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Can you update the guest list in realtime too?

**Comment by frankrousseau** [comment]
It's a subject for another issue.

**Comment by jsilvestre** [comment]
I agree, thank you!

**Comment by frankrousseau** [comment]
The update of the hours field is still broken.

**Pull request merged**
