### PR TITLE
[WIP] Clean up and new build tool

### PR DESCRIPTION
**Pull request by aenario**
This PR includes several changes : we switch to cozy-regular-build (corbu), an unified build tool.
- Corbu has some opinions on where things should go server-side, so we
  1. move `client/*.jade` & `mails/*.jade` to server/views
  2. move server assets (cozy logo for mails) to `server/assets`
  3. move mails/handler to libs (not necessary, but it is a lib)
  4. copy locales to server/locales
- Corbu doesnt like warnings, so we remove all deprecations.
- Corbu include a linter, we lint the application accordingly, it fixes some errors paths
- Corbu supports both webpack & brunch, but we switch to webpack as its "the future" and fix the bug with wrong client after update.
- Corbu setup changed travis to NPM publish on git tags, this was not properly tested, I will take some time to check if it works when we next release calendar.

Things we might want to do in the future : 
- Change corbu to lint following cozy-guidelines (https://github.com/cozy/cozy-regular-build/issues/4) and lint calendar appropriately
- Separate, in transifex or through corbu server locales from client locales. Make emails translation rely on locales instead of separate jade file as it scales better to other langs than french & english.

### CODE REVIEW

**Comment by frankrousseau** [comment]
It looks awesome @aenario but could you make the build green on Travis?

**Comment by aenario** [comment]
I am leaving this PR in standby as we should make a release of Calendar in today or tommorow. 
I will update & fix travis afterward.

**Comment by frankrousseau** [comment]
@aenario what is the state of this PR? I think we published a new version of Calendar. But the build is still red.

**Comment by nono** [comment]
@aenario do you think we should keep this PR? It looks like you won't have time to finish it and it has diverged a lot from the master.

**Pull request closed without merging**
