### PR TITLE
Put back the week view

### PR DESCRIPTION
**Pull request by frankrousseau**
Hi,

I noticed that many people from the community (#528) wanted to see the week view back. I remembered it worked before. So I tried to put it back. It required some debugging and dirty hacks (I hope you won't mind). 

With the following changes, it seems to work fine on Chrome and Firefox on Linux and MacOS. But I can't guarantee that it doesn't bring any regression.

### CODE REVIEW

**Comment by jsilvestre** [comment]
I did not manage to build the application, or start it in dev mode. @aenario can you have a look please? I know @gregorylegarec succeeded without any probleme a few weeks ago so it's probably just me. If you could build me a branch somewhere that would be great :3

Joseph.

**Comment by jsilvestre** [comment]
Thank you @aenario, and thank you @frankrousseau it works well! I'll let someone technical merge it and release it :)

**Comment by frankrousseau** [comment]
Yep the build looks broken. I didn't manage to make it work on my second computer.

**Comment by aenario** [comment]
Merci @frankrousseau ! Released as v1.0.47

**Comment by clochix** [comment]
That's awesome, it's something our community asked for months, thanks a lot @frankrousseau 😍 !!!

**Pull request merged**
