### PR TITLE
fix(icon missing): #223 changed icon name for 'duplicate link'

### PR DESCRIPTION
**Pull request by sylzys**
Icon is not showing.

It seems a bit too far left.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Ok thanks. It looks like there is a problem with the icon font.

**Comment by frankrousseau** [comment]
Thank you for that proposal. We'll have a look at it soon.

**Comment by jsilvestre** [comment]
Thank you for the PR. Can you please rebase the PR against the current master?

**Comment by sylzys** [comment]
Rebase should be ok

**Comment by m4dz** [comment]
Nice, thanks! The icon is actually is little bit too far left but this is due to the poor consistency of glyphicon. I'll fix that in another PR, replacing icons with FontAwesome ones :smile:.

**Pull request merged**
