### PR TITLE
Improve french strings

### PR DESCRIPTION
**Pull request by NumEricR**
Hello,

Here some changes to improve french translation.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Hi @NumEricR,

It looks like the way we write event is right:

https://fr.wikipedia.org/wiki/%C3%89v%C3%A9nement

**Comment by NumEricR** [comment]
Yes both are right but I think it should be better to use only one spelling.
Currently we can see "[événement](https://github.com/cozy/cozy-calendar/blob/master/client/app/locales/fr.coffee#L16)" AND "[évènement](https://github.com/cozy/cozy-calendar/blob/master/client/app/locales/fr.coffee#L5)" in cozy calendar.

**Comment by jsilvestre** [comment]
Thank you @NumEricR, you are right, it should be the same everywhere. Let's ask @goofy-bz what he thinks about it: "événement" or "évènement". goofy is our  Cozy Official French Master (tm).

**Comment by goofy-bz** [comment]
Thanks @NumEricR for rising this issue, this is a valid point, of course same choice should apply everywhere as suggested. I approve his suggestion for « évènement » (yes the other accent would be valid too) because it is recommended since 1990 (hey 25 years ago, you cannot call it "nouvelle orthographe" by now)
For reference https://fr.wiktionary.org/wiki/Annexe:Rectifications_orthographiques_du_fran%C3%A7ais_en_1990#Accent_grave_au_lieu_de_l.E2.80.99accent_aigu

**Comment by frankrousseau** [comment]
Thank you all for your participation. I was not able to decide alone.

**Comment by NumEricR** [comment]
No problemo :)

Still happy to help you guys!

**Pull request merged**
